// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJytCXQ5IkHTw-89vmHxeyAT3C_43QlQo',
    appId: '1:867349106505:web:4673847cd8f39ab4cc9498',
    messagingSenderId: '867349106505',
    projectId: 'psoft-task',
    authDomain: 'psoft-task.firebaseapp.com',
    databaseURL: 'https://psoft-task-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'psoft-task.appspot.com',
    measurementId: 'G-03PK91RH5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBME6KsRTr8m7pKO4hclIbXEMXlXckRQ',
    appId: '1:867349106505:android:56ae5f8e1b8d7eb0cc9498',
    messagingSenderId: '867349106505',
    projectId: 'psoft-task',
    databaseURL: 'https://psoft-task-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'psoft-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhj_qBN6vT6AI8Y_Z7dznPH5YvecZ11hw',
    appId: '1:867349106505:ios:fc953d51e68a19cacc9498',
    messagingSenderId: '867349106505',
    projectId: 'psoft-task',
    databaseURL: 'https://psoft-task-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'psoft-task.appspot.com',
    androidClientId: '867349106505-pvrcionpqer0c2i3suf75ngrsk6vf5cv.apps.googleusercontent.com',
    iosClientId: '867349106505-p8ikcskef3i3fmm0gjsld5q9dpm673lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhj_qBN6vT6AI8Y_Z7dznPH5YvecZ11hw',
    appId: '1:867349106505:ios:fc953d51e68a19cacc9498',
    messagingSenderId: '867349106505',
    projectId: 'psoft-task',
    databaseURL: 'https://psoft-task-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'psoft-task.appspot.com',
    androidClientId: '867349106505-pvrcionpqer0c2i3suf75ngrsk6vf5cv.apps.googleusercontent.com',
    iosClientId: '867349106505-p8ikcskef3i3fmm0gjsld5q9dpm673lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJytCXQ5IkHTw-89vmHxeyAT3C_43QlQo',
    appId: '1:867349106505:web:7378dda0e2d11d8fcc9498',
    messagingSenderId: '867349106505',
    projectId: 'psoft-task',
    authDomain: 'psoft-task.firebaseapp.com',
    databaseURL: 'https://psoft-task-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'psoft-task.appspot.com',
    measurementId: 'G-RB4D0FEXL8',
  );

}